version: "3.3"
services:
  backend:
    container_name: "clientipviewer"
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "8080:80"
  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"
    # command: nginx -t